### PR TITLE
Compress PNG

### PR DESCRIPTION
**Pull request by Malvoz**
Compress PNGs, same as in https://github.com/Maps4HTML/FiskMississippiMapsStreamCourses/pull/2.

Result is 23.9 MB => 3.37 MB.

Here's a [sample comparison](https://github.com/Maps4HTML/TiledArt-Rousseau/pull/1/commits/32f4519bb57f9fb46b9702d58b1f01b8f77b734d?short_path=e04f24e#diff-e04f24eee3d47b95e8d58fdf1155182a) of uncompressed (100 KB) vs compressed (18.4 KB).

### CODE REVIEW

**Comment by Malvoz** [comment]
cc @AmeliaBR, @NickFitz

**Comment by AmeliaBR** [comment]
Again, great idea to run them through the compressor.

I'm a little worried it might be a little too compressed, though. There's a lot of color lost in the palette, see e.g. [this file diff](https://github.com/Maps4HTML/TiledArt-Rousseau/pull/1/files?short_path=34d734f#diff-49eeaf9c347caabe5e40c4b8052a44fc).

Now, this isn't actually a production website for a gallery — we don't need to ensure true representation of the original. But, we do need to make sure the tiled result still looks continuous. What settings were you using to compress? Was it automatically calculating the palette for each PNG individually, or did you pick a palette for the full (zoomed-out) image and then force it for all the tiles? Have you tested it in the map viewers to see if it looks OK?

**Comment by Malvoz** [comment]
Ok I reverted and compressed with a different quality setting, apparently the default setting only allows for images to be compressed to quality between 20-50% of the original image, I changed this to 70-90% instead. The end result is a total of 7,81 MB (instead of 3.37 MB in first commit) from 23.9 MB, but the images look way better now.

Compare this [image in the initial commit (88 => 11 KB)](https://github.com/Maps4HTML/TiledArt-Rousseau/pull/1/commits/32f4519bb57f9fb46b9702d58b1f01b8f77b734d?short_path=49eeaf9#diff-49eeaf9c347caabe5e40c4b8052a44fc), to the higher quality [image in the latter commit (88 => 29 KB)](https://github.com/Maps4HTML/TiledArt-Rousseau/pull/1/commits/8089efefe07aa8b1dee6fc658ecd5dac1de84ce3?short_path=49eeaf9#diff-49eeaf9c347caabe5e40c4b8052a44fc).

**Comment by AmeliaBR** [comment]
Thanks Malvoz! I think this is probably a good balance between capturing the potential quality while respecting data plans.

**Pull request merged**
